### ISSUE TITLE
automate the fetching of the mrjs README file

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/documentation#14]
The MRJS README file is getting regularely updated.
Currently grabbing the latest file in this repo is a manual process. Let's automate it.

**Comment by hanbollar** [comment]
already have that happening per these commits now - :D

https://github.com/Volumetrics-io/documentation/commit/3aaa4b15fc772420451312f0a93bbd3845573fea

if that's not what you mean, lmk

**Comment by hanbollar** [comment]
on discord confirmed, all good ~
