### ISSUE TITLE
Fix the MRjs spelling in the JavaScript API doc

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/documentation#17]
There are only 3 places where we need to update the spelling for MRjs:

![image](https://github.com/Volumetrics-io/documentation/assets/6750584/de86698d-817e-41d6-9d52-14f63e212ca9)
At the beginning in `MRElement`

![image](https://github.com/Volumetrics-io/documentation/assets/6750584/73686da5-1907-45aa-9106-9573a6ea8f6b)
In the `Physics.CollisionGroups`

![image](https://github.com/Volumetrics-io/documentation/assets/6750584/7f8cd264-6a39-4f2d-8213-0a0384324808)
In the `MRPlaneManager`

If we could be consistent everywhere with `MRjs` that would be awesome.
This is not urgent!

**Comment by hanbollar** [comment]
Fixed by https://github.com/Volumetrics-io/mrjs/commit/e2084620bf6f5bb3b1f8950c38bd38b173bd3c0b

and its follow on in this repo: https://github.com/Volumetrics-io/documentation/commit/77421c3f9747f01157bec745b2a0005ce08f6546
