### ISSUE TITLE
Fix `mr-textfield` sample code

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/documentation#18]
Based on this MRjs bug https://github.com/Volumetrics-io/mrjs/issues/422
We need to fix the doc and sample code for `mr-textfield` when the fix lands

**Comment by hanbollar** [comment]
heads up, @lobau https://github.com/Volumetrics-io/mrjs/issues/422 is now closed

**Comment by hanbollar** [comment]
this will be cleaned up in #19
